name: databricks-cicd

on: [workflow_dispatch]

jobs:
    db_azure:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            
            
            - name: Install databricks CLI
              run: |
                curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
            
            - name: List databricks repo
              env: 
                DATABRICKS_HOST: ${{ vars.HOST }}
                DATABRICKS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              run: |
                databricks repos list
            
            - name: databricks-import
              uses: microsoft/databricks-import-notebook@v1.0.0
              with:
                databricks-host: ${{ vars.HOST }}
                databricks-token: ${{ secrets.ACCESS_TOKEN }}
                local-path: $GITHUB_WORKSPACE/wiews_data_upsert_mode.py
                remote-path: "http://users/burak_doguu_hotmail.com#ext#@burakdoguuhotmail.onmicrosoft.com"